// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKn180rtmKjV77Fkqe2go3US0rtX-r5Y4',
    appId: '1:875905941683:web:c15526b9e5bec0741c30c6',
    messagingSenderId: '875905941683',
    projectId: 'pawbuddy-e9ae9',
    authDomain: 'pawbuddy-e9ae9.firebaseapp.com',
    storageBucket: 'pawbuddy-e9ae9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALYyAJkgBX3NdxGJVeeP8M9OQO3hpmPtU',
    appId: '1:875905941683:android:25dc919cc643e33c1c30c6',
    messagingSenderId: '875905941683',
    projectId: 'pawbuddy-e9ae9',
    storageBucket: 'pawbuddy-e9ae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8thdslJgCYcYJAnooN74lmOR0xRUrSE',
    appId: '1:875905941683:ios:64b7e3c71f531b621c30c6',
    messagingSenderId: '875905941683',
    projectId: 'pawbuddy-e9ae9',
    storageBucket: 'pawbuddy-e9ae9.appspot.com',
    iosBundleId: 'com.example.pawbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO8thdslJgCYcYJAnooN74lmOR0xRUrSE',
    appId: '1:875905941683:ios:64b7e3c71f531b621c30c6',
    messagingSenderId: '875905941683',
    projectId: 'pawbuddy-e9ae9',
    storageBucket: 'pawbuddy-e9ae9.appspot.com',
    iosBundleId: 'com.example.pawbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKn180rtmKjV77Fkqe2go3US0rtX-r5Y4',
    appId: '1:875905941683:web:5c2b945f3fae217b1c30c6',
    messagingSenderId: '875905941683',
    projectId: 'pawbuddy-e9ae9',
    authDomain: 'pawbuddy-e9ae9.firebaseapp.com',
    storageBucket: 'pawbuddy-e9ae9.appspot.com',
  );

}